-dontwarn org.flywaydb.core.internal.**
-dontwarn org.flywaydb.core.api.migration.spring.**
-dontwarn org.flywaydb.core.api.configuration.S3ClientFactory
-dontwarn org.flywaydb.core.Flyway
-keep class org.flywaydb.core.** { *; }
-keep class com.google.gson.** { *; }
-keep class org.sqlite.** { *; }
-keepdirectories db/migrations/**